name: M-x Kelsin
desc: Hacking, Hacking, Hacking
author:
  name: Christopher Giroir
  email: kelsin@valefor.com
markdown: redcarpet
pygments: true
paginate: 5
exclude:
  - .bowerrc
  - bower.json
  - .bundle
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
social:
  github: kelsin
  facebook: kelsin
  twitter: kelsin5
  rdio: kelsin
  # linkedin: kelsin
  # gplus: ChristopherGiroir
  # lastfm: Kelsin
