# Blog author setup
name: M-x Kelsin
desc: A Hacking Blog
author:
  name: Christopher Giroir
  email: kelsin@valefor.com

# Blog page setup
permalink: /:year/:month/:day/:title/
baseurl: /
url: http://mx.kelsin.net/
paginate: 5
encoding: UTF-8

# Markdown settings
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data
    - strikethrough
    - smart

# Syntax Highlighting
pygments: true

# Approved github jekyll plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Ignore files meant for building
exclude:
  - .bowerrc
  - .bundle
  - .ruby-version
  - bower.json
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json

# Analytics
analytics:
  google: UA-24773156-4

# Social links
social:
  github: kelsin
  facebook: kelsin
  twitter: kelsin5
  rdio: kelsin
  bandcamp: kelsin
  # spotify: kelsin
  # linkedin: kelsin
  # gplus: ChristopherGiroir
  # lastfm: Kelsin
